# Generated by Django 5.0 on 2024-11-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usermodels',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email'),
        ),
    ]
